name: Build libclc
on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
      - name: Setup Ninja
        uses: ./.github/actions/setup-ninja
      - name: Fetch sources
        run: |
          git clone -b master --depth 1 https://github.com/google/clspv.git clspv
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: libclc
      - name: Configure
        shell: bash
        run: |
          python ../clspv/utils/fetch_sources.py --shallow --deps llvm
          cmake -B build ../clspv -G Ninja \
            -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
            -DCMAKE_BUILD_TYPE=Release \
      - name: Build
        run: |
          cmake --build ./build -j3 clspv--.bc clspv64--.bc
          ls ./build/third_party/llvm/libclc/
      - uses: actions/upload-artifact@v4
        with:
          name: libclc
          path: ./build/third_party/llvm/libclc/
